- posframe.el
There's no need for the hack on macOS, so it makes sense to disable it by default.
> Disable posframe-mouse-banish on macOS

- posframe.el
Hi, I'm AndyStewart from EmacsWiki, your posframe.el is awesome.
I found posframe--run-timeout-timer will trigger error once developer use posframe-delete remove frame before posframe timer.
Error running timer ‘make-frame-invisible’: (wrong-type-argument frame-live-p #<dead frame *sdcv* 0x63e7940>)
I build a new function posframe-hide-frame instead make-frame-invisible that use frame-live-p check frame before delete.
> Use posframe-hide-frame instead make-frame-invisible

- posframe.el
For macOS window manager chunkwm, it uses title to avoid tiling tooltip, thought
posframe should work the same way.
> use empty posframe title for window manager

- posframe.el
In text mode, the function `font-at` returns nil.  Meanwhile
`font-info` expects a string.
> Make posframe work for `emacs -nw`

- posframe.el
- I am trying to use posframe to create a floating control for dap-mode which
will have Step in/Step out/Continue, etc buttons (see screenshot). The problem
that I am facing is that when posframe-show which is called when the new set of
buttons is enabled is performed when current-frame the posframe itself. In order
to solve that in our code I used
``` elisp
(when (eq (selected-frame) pos-frame)
(select-frame (frame-parent pos-frame)))
```
But when I do that from time to time the buffer in the posframe chamges. The
following piece of code fixes the issue.
> Make the buffer in posframe dedicated

- posframe.el
This PR makes posframe automatically redirect input focus back to the previous frame when the posframe gets focus. This seems to fix the issue where the posframe erroneously grabs the keyboard input when it appears under the mouse cursor in some window managers.
This should make the option `posframe-mouse-banish` unnecessary, however I didn't remove it in this PR in case some people would still want it. If you think I should remove that option, just let me know.
I also wrote [a comment](https://github.com/tumashu/posframe/issues/27#issuecomment-554693252) on issue #27 about this solution as well.
> prevent posframes from getting keyboard input

- posframe.el
This is improved #56. 
* posframe.el (posframe--set-frame-size):
Set `posframe--last-posframe-size` even when width or height is nil. ( This is to set min-height and min-width)
* posframe.el (posframe--run-refresh-timer):
* posframe.el (posframe-refresh):
Bind `frame-resize-pixelwise` to t before calling `fit-frame-to-buffer`.
> Fix incorrect posframe size after posframe-refresh

- posframe.el
This is to simplify the `posframe--redirect-posframe-focus` function code.
Actually, for me, this is not only for code simplification because I found a very tricky case that this function doesn't work properly on Xmonad WM.
In short, on Xmoand, run Emacs, move to the other workspace, come back to Emacs, put cursor where posframe would pop up, and do run posframe command. Then `(eq (selected-frame) (posframe))` is true but `posframe--previous-frame` is still `nil`, therefore focus redirection does not happen.
I tested this on Gnome DE, Awesome WM and Xmonad and this weird thing happened only on Xmonad. So, this might be a case by a bug of Xmoand. 
So, you may value this pull request just in term of code simplification and consider to merge or not. 
Thank you.
> posframe.el (posframe--redirect-posframe-focus): simplify

- posframe.el
I was trying to find a way to truncate lines in the posframe display, but the that variable is hardcoded to always wrap. This PR gives the option to let the user specify the `truncate-lines` setting, defaulting to `nil`.
> Allow users to truncate lines in posframe

- posframe.el
With `poshandler` set to `posframe-poshandler-frame-bottom-right-corner`, the posframe will not be displayed properly once a bigger frame has been displayed.
To repo this issue, try this snippet
``` elisp
(cl-labels ((show (content time)
(run-at-time time nil
(lambda (content)
(with-current-buffer (get-buffer-create "*a*")
(erase-buffer)
(insert content))
(posframe-show (get-buffer-create "*a*")
:poshandler #'posframe-poshandler-frame-bottom-right-corner
:internal-border-width 1
:internal-border-color "white"))
content)))
(show "aaaaa" 1)
(show "aa" 2))
```
And how it looks like
The problem is `posframe-show` will call `posframe--set-frame-position` and since the position is the same (relative from right edge and bottom), it will not trigger `set-frame-position` again.
Well, the child …
> posfram--set-frame-position: also set position when frame size changed

- posframe.el
* posframe.el (posframe--redirect-posframe-focus): Deal with posframe accept focus.
(posframe--mouse-banish): Deal with posframe accept focus.
(posframe-show): banish mouse after posframe create.
(posframe--mouse-banish): Add posframe argument.
> Fix: Add the option to disable focus redirection #76

- posframe.el
Two fixes:
- Broken posframe-pshandler-frame-bottom-center on OS X
- Detect gnome session also under wayland. See also https://github.com/sebastiencs/company-box/issues/44
> Minor fixes

- posframe.el
Dear mainterainers:
Thanks for creating `posframe`. I use it as my daily driver.
I write small functions that use `posframe` to show the @nobiot 's new package [org-marginalia](https://github.com/nobiot/org-marginalia).
As an inexperienced elisp player, there must be a more elegant solution. Suggestions are welcome.
Thank you.
> Add a package that uses posframe

- posframe.el
See https://debbugs.gnu.org/cgi/bugreport.cgi?bug=45748
The bug impacts company-posframe when displaying a single result by truncating the last line. It also makes company-posframe truncate the last padding space when displaying multiple results.
This will have the effect of resizing the frame to include leading and trailing newlines as well, which is probably the desired behavior anyway so there's no need to scroll.
> Fix frame fit when there are leading or trailing spaces

- posframe.el
We only use `posframe--redirect-posframe-focus` for Emacs versions
before 27.1, so don't warn about that being obsolete when using that
or a later version; we know.
> Silence byte-compiler

- posframe.el
Hello, I am using `posframe.el` in [mozc-posframe](https://github.com/akirak/mozc-posframe).
A recent change (62ca653b7256b6ad88cd7768d370eea483931168) seems to have caused a new bug (https://github.com/akirak/mozc-posframe/issues/6):
> posframe-delete-frame: Attempt to delete the sole visible or iconified frame
I think this PR will fix the issue. Could you review this PR? Thank you for developing this package.
> Check non-nullity of the buffer

- posframe.el
The byte-compiler recently got more fussy about quotes.
> Replace certain single quotes in docstrings

- posframe.el
Hi,
I noticed that currently, the posframe is always redrawn even when it is created for the first time.
This makes the background of the posframe become flashing (disappears and appears again very quickly)
This PR fixes this issue by only redrawing when reusing the existing frame.
Can you take a look and merge if it's useful?
Thanks!
> only redraw when reusing the existing posframe

- posframe.el
Hi,
I'm using Emacs for MacOS (https://emacsformacosx.com), and when running Helm posframe, Emacs always flickers when showing the posframe. 
The reason is that the posframe frame is first created at location `(0, 0)`, and it is supposed to be invisible, and will be moved to the desired position later. However, in Emacs for MacOS, somehow the posframe was visible before it is moved to the new location, which causes the flickering.
In this PR, I fixed this issue by supplying the position information (if it is available in the form of `(left . top)`), so that the posframe is created at the desired location when `position` is supplied.
Can you review this PR and merge it if possible?
Thanks!
> configure posframe position during creation if position is available

- posframe.el
posframe-hide should not attempt to make non-posframe frames invisible.
Debugger entered--Lisp error: (error "Attempt to make invisible the sole visible or icon...")
posframe--make-frame-invisible(#<frame *scratch* 0x1489bb230>)
posframe-hide(nil)
vertico-posframe-mode(0)
...
(posframe-hide nil) can attempt to hide *scratch* buffer's frame accidentally.
vertico-posframe also has an issue though.
```
#+begin_example
Debugger entered--Lisp error: (error "Attempt to make invisible the sole visible or icon...")
posframe--make-frame-invisible(#<frame *scratch* 0x1489bb230>)
posframe-hide(nil)
vertico-posframe-mode(0)
(closure (bootstrap-version t) nil (vertico-posframe-mode (if (my/posframe-after-focus-change-p) 1 0)))()
apply((closure (bootstrap-version t) nil (vertico-posframe-mode (if …
```
> Check if given BUFFER-OR-NAME is non-nil in posframe-hide

- posframe.el
Hi,
Currently, I notice that `posframe` does not update the posframe position corresponding to the current point if I run `recenter-top-bottom` on the target buffer.
This issue happened in <https://github.com/alexmurray/flycheck-posframe>
So, I created this PR to update the `window-start` and `window-end` position to force `posframe` recompute a new position when the `window-start` and `window-end` are changed (for example, by `recenter-top-bottom`).
Can you consider merging this PR?
Thanks!
> store window start, end position into last position info

- posframe.el
This is the same behavior with [corfu](https://github.com/minad/corfu/blob/b779552341354d59365a981fd208ae07b7a2950a/corfu.el#L464)
> Use parent's minibuffer window

- posframe.el
Same as this [PR](https://github.com/tumashu/vertico-posframe/pull/45).
> Prevent running inside a minibuffer-only frame

- posframe.el
When the current buffer is a minibuffer, use the height of the mode-line
of the window above it.  Without this the posframe covers the mode-line
when using, e.g., `posframe-poshandler-frame-bottom-right-corner` and
the `posframe-show` is called while the minibuffer is active.
The other two commits clean up whitespace and docstrings.
> posframe-show: Take mode-line-height into account from minibuffer
